name: On pull request
on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    timeout-minutes: 30
      steps:
        - name: run test
          uses: npm
          run: npm run test

  